# Generated by Django 2.1.8 on 2019-09-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_login', '0003_goods_goods_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/static/images/default.jpg/', upload_to='images'),
        ),
    ]
