# Generated by Django 2.1.8 on 2019-09-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_login', '0004_auto_20190906_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/static/img/default.jpg/', upload_to='images'),
        ),
    ]
