# Generated by Django 2.1.8 on 2019-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_login', '0007_auto_20190906_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
